### ISSUE TITLE
Verlinkung eures Beitrages im Haupt-Repository

### ISSUE THREAD

**Issue by jonico** [sebastianvolk/informatiCup2020#45]
👋 @sebastianvolk, @MaikG90, @danial0 and @mirweis, 

bis jetzt haben wir eure tolle Einsendung noch nicht in https://github.com/informatiCup/informatiCup2020/tree/master/github-sonderpreis gesehen, wollt ihr einen pull-request stellen?

Liebe Grüße und frohe Ostern

@jonico

:octocat: ❤️

**Comment by sebastianvolk** [comment]
Hi @jonico 

danke für die Erinnerung. Wir haben jetzt einen pull-request erstellt.

Viele Grüße und auch von uns schöne Osterfeiertage
@MaikG90 @mirweis @danial0 @sebastianvolk
